services:
  web:
    build: .
    command: bash -c "ruby hello.rb -p 4567 -o '0.0.0.0'"
    ports:
      - "4567:4567"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=sinatra
      - POSTGRES_PASSWORD=sinatra
    depends_on:
      - web
    ports:
      - "5432:5432"

