default: &default
  adapter: postgresql
  encoding: unicode
  host: sinatra_db
  username: 'sinatra'
  password: 'sinatra'
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sinatra_app_development

test:
  <<: *default
  database: sinatra_app_test
